/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.struts.action;

import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.smart.struts.dao.StateInfoDao;
import com.smart.struts.form.AddStateInfoForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-08-2011
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/AddMinister.jsp"
 * @struts.action-forward name="failure" path="/index.jsp"
 */
public class AddMinisterAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws SQLException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException {
		// TODO Auto-generated method stub
		AddStateInfoForm mf=(AddStateInfoForm)form;
		boolean flag=new StateInfoDao().addMinisters(mf);
		if(flag)
			return mapping.findForward("success");
		else
			return mapping.findForward("failure");
	}
}