/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.struts.action;

import java.io.FileNotFoundException;
import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.smart.struts.dao.CityInfoDao;
import com.smart.struts.form.BusRouteForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-09-2011
 * 
 * XDoclet definition:
 * @struts.action path="/busRoute" name="busRouteForm" input="/form/busRoute.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/AddBusRoutes.jsp"
 * @struts.action-forward name="failure" path="/index.jsp"
 */
public class BusRouteAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws SQLException 
	 * @throws FileNotFoundException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException {
		BusRouteForm br = (BusRouteForm) form;// TODO Auto-generated method stub
		boolean flag=new CityInfoDao().addBusRoute(br);
		String city=request.getParameter("cityid");
		System.out.println("ciiiii"+city);
		if(flag)
			return mapping.findForward("success");
		else
			return mapping.findForward("failure");
	}
}