/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.struts.action;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.smart.struts.dao.MessageDAO;
import com.smart.struts.form.MessageForm;
import com.smart.util.DateWrapper;
import com.smart.util.LoggerManager;

/** 
 * MyEclipse Struts
 * Creation date: 08-14-2011
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/index.jsp"
 * @struts.action-forward name="failure" path="/index.jsp"
 */
public class ComposeAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub

	     boolean flag=false;
	     try
	     {
	     	String from = request.getParameter("from");
	     	String to = request.getParameter("to");
	     	String subject = request.getParameter("subject");
	     	String message = request.getParameter("message");
	     
	   		MessageForm messagedto = new MessageForm();
	     	messagedto.setFrom(from);
	     	messagedto.setTo(to);
	     	messagedto.setSenddate(DateWrapper.parseDate(new Date()));
	     	messagedto.setSubject(subject);
	     	messagedto.setMessage(message);
	     
	     	flag = new MessageDAO().sendMessage(messagedto);
	      }
	      catch(Exception e)
	      {
	        LoggerManager.writeLogSevere(e);
	      }
	      if(flag)
	       		return mapping.findForward("success");
	     	else
	       		return mapping.findForward("failure");
	     	
	}
}