/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.struts.action;

import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.smart.struts.dao.TheatresDao;
import com.smart.struts.form.BusRouteForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-09-2011
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/ViewMinisters.jsp"
 * @struts.action-forward name="failure" path="/ViewMinisters.jsp"
 */
public class DeleteTheatreAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws SQLException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException {
		// TODO Auto-generated method stub
		BusRouteForm af=(BusRouteForm)form;
		boolean flag=false,flag1=false; 
		  String responsekey="failure";
	      	
		  String check[] = request.getParameterValues("check");
		  for(int i=0;i<check.length;i++)
		  {
		  		String temp = check[i];
		  		flag=new TheatresDao().deleteTheatre(Integer.parseInt(temp));
		  }
		  if(flag)
		  { 
			  responsekey="success";
		  }	  
		  else
		  {
			   responsekey="failure";
		  }	   
		  return mapping.findForward(responsekey);
	}
}