/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.struts.action;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.smart.struts.dao.MessageDAO;
import com.smart.util.LoggerManager;

/** 
 * MyEclipse Struts
 * Creation date: 08-14-2011
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/index.jsp"
 * @struts.action-forward name="failure" path="/index.jsp"
 */
public class DeleteMsgAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException 
	 * @throws ServletException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		int count = 0;
		   String pathstring=request.getParameter("page");
		   String field="",responsekey="";
		   if(pathstring.equals("ViewInbox.jsp") || pathstring.equals("AViewInbox.jsp"))
		      field = "receiverstatus";
		   else 
		      field = "senderstatus";  
		  try{
		    MessageDAO msgdao = new MessageDAO();
		    String param[] = request.getParameterValues("ch");
		    for(int i=0;i<param.length;i++)
		    {
		       if(msgdao.changeMessageStatus(Integer.parseInt(param[i]),field)) 
		            count++;
		    }
		    }catch(Exception e)
		    {
		      LoggerManager.writeLogSevere(e);
		    }
		    
		   if(count>0)
		   {
			   return mapping.findForward("success");
		   }
		    	
		    else
		    	return mapping.findForward("failure");
		    
	}
}