/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.struts.action;

import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.smart.struts.dao.SecurityDAO;
import com.smart.struts.form.RegisterForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-14-2011
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="user" path="/UserHome.jsp"
 * @struts.action-forward name="admin" path="/AdminHome.jsp"
 * @struts.action-forward name="failure" path="/index.jsp"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws SQLException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException {
		// TODO Auto-generated method stub
		String target = "index.jsp?status=Invalid username and password";
		String role=null,username=null,responsekey=null;
		try{
		
			RegisterForm  rb=new RegisterForm();
			
		 username = request.getParameter("username");
         rb.setLoginname(username);
         
         rb.setPassword(request.getParameter("password"));
         
          role=new SecurityDAO().loginCheck(rb);
         System.out.println("rrrrr"+role);
	}catch(Exception e){}
        HttpSession session=request.getSession();
		if(role.equals("admin"))
         { 
            target = "adminhome.jsp?status=Welcome "+username;
            session.setAttribute("user",username);
            session.setAttribute("role",role);
            responsekey="admin";
         } 
         else if(role.equalsIgnoreCase("user"))
         {
            int status = new SecurityDAO().checkFirstLogin(username);
            System.out.println("ssss"+status);
           if(status==1)
            	responsekey="user";
            else
            	responsekey="failure";
            session.setAttribute("user",username);
            session.setAttribute("role",role);
         } 
         else if(role.equalsIgnoreCase("emp"))
         {
            int status = new SecurityDAO().checkLoginStatus(username);
            System.out.println("status"+status);
           if(status==1)
            	responsekey="emp";
           else if(status==0)
        	   responsekey="failure";
            
            else
                target = "LoginForm.jsp?status=Invalid username and password";    	
            session.setAttribute("user",username);
            session.setAttribute("role",role);
         } 
         else if(role.equalsIgnoreCase("detective"))
         {
            int status = new SecurityDAO().checkLoginStatus(username);
            System.out.println("status"+status);
           if(status==1)
            	responsekey="detective";
           else if(status==0)
        	   responsekey="failure";
            
            else
                target = "LoginForm.jsp?status=Invalid username and password";    	
            session.setAttribute("user",username);
            session.setAttribute("role",role);
         } 
         else  
        	 return mapping.findForward("failure");
            
         return mapping.findForward(responsekey);
	}
}