/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.struts.action;

import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.smart.struts.dao.CityInfoDao;
import com.smart.struts.form.AlertForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-13-2011
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/MailAlerts.jsp"
 * @struts.action-forward name="failure" path="/index.jsp"
 */
public class SubscribeAlertsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws SQLException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws SQLException {
		// TODO Auto-generated method stub
		AlertForm af=(AlertForm)form;
		boolean flag=false;
		String str[]=request.getParameterValues("list");
		String str1="";
	
		for(int i=0;i<str.length;i++)
		{
			System.out.println("------"+str[i]);
			af.setAlerttype(str[i]);
	        //flag=new CityInfoDao().subscribeAlerts(af);
	        if(request.getParameter("submit").equalsIgnoreCase("Subscribe"))
		  		   flag=new CityInfoDao().subscribeAlerts(af);
		  	else
		  		   flag=new CityInfoDao().unsubscribeAlerts(af);
		}
		
		if(flag)
			return mapping.findForward("success");
		else
			return mapping.findForward("failure");
	}
}