/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.struts.action;

import java.io.FileNotFoundException;
import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.smart.struts.dao.BusinessInfoDao;
import com.smart.struts.form.BusinessInfoForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-11-2011
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="failure" path="/upbusiness.jsp"
 * @struts.action-forward name="sucess" path="/upbusiness.jsp"
 */
public class UpBusinesActionAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws SQLException 
	 * @throws FileNotFoundException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws FileNotFoundException, SQLException {
		BusinessInfoForm ab = (BusinessInfoForm) form;// TODO Auto-generated method stub
        BusinessInfoDao sd=new BusinessInfoDao();
	    boolean flag=sd.businessupdate(ab);
		if(flag)
			return mapping.findForward("success");
		else
			return mapping.findForward("failure");
		}
	
}