/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.struts.action;

import java.io.FileNotFoundException;
import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.smart.struts.dao.CityInfoDao;
import com.smart.struts.form.AddCityInfoForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-24-2011
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/updatestates.jsp"
 * @struts.action-forward name="failure" path="/updatestates.jsp"
 */
public class UpdateCitiesAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws SQLException 
	 * @throws FileNotFoundException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws FileNotFoundException, SQLException {
		 boolean flag=false;
		try{
		AddCityInfoForm as= (AddCityInfoForm) form;
		HttpSession session=request.getSession();
		CityInfoDao sd=new CityInfoDao();
		
	     flag=sd.updatecity_info(as);
		
		}
		catch (Exception e) {
			e.printStackTrace();
		}
		if(flag)
			return mapping.findForward("success");
		else
			return mapping.findForward("failure");
	}
	
}