/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smartcity.struts.action;

import java.io.FileNotFoundException;
import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.smart.struts.dao.StateInfoDao;
import com.smartcity.struts.form.StateForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-01-2011
 * 
 * XDoclet definition:
 * @struts.action path="/state" name="stateForm" input="/form/state.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/stateinfo.jsp"
 * @struts.action-forward name="failure" path="/stateinfo.jsp"
 */
public class StateAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws SQLException 
	 * @throws FileNotFoundException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws FileNotFoundException, SQLException {
		StateForm stat = (StateForm) form;// TODO Auto-generated method stub
		StateInfoDao sd=new StateInfoDao();
	    boolean flag=sd.state_info(stat);
		if(flag)
			return mapping.findForward("success");
		else
			return mapping.findForward("failure");
		}
	}
