/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 09-09-2011
 * 
 * XDoclet definition:
 * @struts.form name="addCityInfoForm"
 */
public class AddCityInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 22708160448125853L;

	/** state_id property */
	private Integer state_id;

	/** zone property */
	private String zone;

	/** city_id property */
	private Integer city_id;

	/** city_name property */
	private String city_name;
	
	
	private String city_map;

	private String history;
	
	private String offaddr;
	
	private String phone;
	
	private String mayor;
	
	private String newspaper;
	
	private String tvchannels;
	
	/*
	 * Generated Methods
	 */

	public String getMayor() {
		return mayor;
	}

	public void setMayor(String mayor) {
		this.mayor = mayor;
	}

	public String getHistory() {
		return history;
	}

	public void setHistory(String history) {
		this.history = history;
	}

	public String getOffaddr() {
		return offaddr;
	}

	public void setOffaddr(String offaddr) {
		this.offaddr = offaddr;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the state_id.
	 * @return Integer
	 */
	public Integer getState_id() {
		return state_id;
	}

	/** 
	 * Set the state_id.
	 * @param state_id The state_id to set
	 */
	public void setState_id(Integer state_id) {
		this.state_id = state_id;
	}

	/** 
	 * Returns the zone.
	 * @return String
	 */
	public String getZone() {
		return zone;
	}

	/** 
	 * Set the zone.
	 * @param zone The zone to set
	 */
	public void setZone(String zone) {
		this.zone = zone;
	}

	/** 
	 * Returns the city_id.
	 * @return Integer
	 */
	public Integer getCity_id() {
		return city_id;
	}

	/** 
	 * Set the city_id.
	 * @param city_id The city_id to set
	 */
	public void setCity_id(Integer city_id) {
		this.city_id = city_id;
	}

	/** 
	 * Returns the city_name.
	 * @return String
	 */
	public String getCity_name() {
		return city_name;
	}

	/** 
	 * Set the city_name.
	 * @param city_name The city_name to set
	 */
	public void setCity_name(String city_name) {
		this.city_name = city_name;
	}

	public String getCity_map() {
		return city_map;
	}

	public void setCity_map(String city_map) {
		this.city_map = city_map;
	}

	public String getNewspaper() {
		return newspaper;
	}

	public void setNewspaper(String newspaper) {
		this.newspaper = newspaper;
	}

	public String getTvchannels() {
		return tvchannels;
	}

	public void setTvchannels(String tvchannels) {
		this.tvchannels = tvchannels;
	}
}