/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;


public class AddStateInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	
	private static final long serialVersionUID = 1L;

	/** state_id property */
	private Integer state_id;

	/** zone property */
	

	/** state_name property */
	private String state_name;

	
	/** capital property */
	private String capital;
	
	private String cm;
	
	private String governor;
	
	private String sitemap;
	
	private String languages;

	private String ministry;
	
	private String minister;
	
	/*
	 * Generated Methods
	 */

	public String getMinistry() {
		return ministry;
	}

	public void setMinistry(String ministry) {
		this.ministry = ministry;
	}

	public String getMinister() {
		return minister;
	}

	public void setMinister(String minister) {
		this.minister = minister;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the state_id.
	 * @return Integer
	 */
	public Integer getState_id() {
		return state_id;
	}

	/** 
	 * Set the state_id.
	 * @param state_id The state_id to set
	 */
	public void setState_id(Integer state_id) {
		this.state_id = state_id;
	}

	
	/** 
	 * Set the state_name.
	 * @param state_name The state_name to set
	 */
	public void setState_name(String state_name) {
		this.state_name = state_name;
	}

	 
	public String getCapital() {
		return capital;
	}

	/** 
	 * Set the capital.
	 * @param capital The capital to set
	 */
	public void setCapital(String capital) {
		this.capital = capital;
	}

	public String getCm() {
		return cm;
	}

	public void setCm(String cm) {
		this.cm = cm;
	}

	public String getGovernor() {
		return governor;
	}

	public void setGovernor(String governor) {
		this.governor = governor;
	}

	public String getSitemap() {
		return sitemap;
	}

	public void setSitemap(String sitemap) {
		this.sitemap = sitemap;
	}

	public String getLanguages() {
		return languages;
	}

	public void setLanguages(String languages) {
		this.languages = languages;
	}

	public String getState_name() {
		return state_name;
	}
}