/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-13-2011
 * 
 * XDoclet definition:
 * @struts.form name="alertForm"
 */
public class AlertForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** city_id property */
	private int city_id;

	/** alert property */
	private String alert;

	/** alerttype property */
	private String alerttype;

	private String username;
	
	private String email;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the city_id.
	 * @return int
	 */
	public int getCity_id() {
		return city_id;
	}

	/** 
	 * Set the city_id.
	 * @param city_id The city_id to set
	 */
	public void setCity_id(int city_id) {
		this.city_id = city_id;
	}

	/** 
	 * Returns the alert.
	 * @return String
	 */
	public String getAlert() {
		return alert;
	}

	/** 
	 * Set the alert.
	 * @param alert The alert to set
	 */
	public void setAlert(String alert) {
		this.alert = alert;
	}

	/** 
	 * Returns the alerttype.
	 * @return String
	 */
	public String getAlerttype() {
		return alerttype;
	}

	/** 
	 * Set the alerttype.
	 * @param alerttype The alerttype to set
	 */
	public void setAlerttype(String alerttype) {
		this.alerttype = alerttype;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
}