/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 09-23-2011
 * 
 * XDoclet definition:
 * @struts.form name="cityHistoryForm"
 */
public class CityHistoryForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** state_id property */
	private Integer state_id;

	/** city_history property */
	private String city_history;

	/** city_image property */
	private String city_image;

	/** city_id property */
	private Integer city_id;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the state_id.
	 * @return Integer
	 */
	public Integer getState_id() {
		return state_id;
	}

	/** 
	 * Set the state_id.
	 * @param state_id The state_id to set
	 */
	public void setState_id(Integer state_id) {
		this.state_id = state_id;
	}

	/** 
	 * Returns the city_history.
	 * @return String
	 */
	public String getCity_history() {
		return city_history;
	}

	/** 
	 * Set the city_history.
	 * @param city_history The city_history to set
	 */
	public void setCity_history(String city_history) {
		this.city_history = city_history;
	}

	/** 
	 * Returns the city_image.
	 * @return String
	 */
	public String getCity_image() {
		return city_image;
	}

	/** 
	 * Set the city_image.
	 * @param city_image The city_image to set
	 */
	public void setCity_image(String city_image) {
		this.city_image = city_image;
	}

	/** 
	 * Returns the city_id.
	 * @return Integer
	 */
	public Integer getCity_id() {
		return city_id;
	}

	/** 
	 * Set the city_id.
	 * @param city_id The city_id to set
	 */
	public void setCity_id(Integer city_id) {
		this.city_id = city_id;
	}
}