/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 09-09-2011
 * 
 * XDoclet definition:
 * @struts.form name="cityTourInfoForm"
 */
public class CityTourInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** state_id property */
	private Integer state_id;

	/** logitude property */
	private String logitude;

	/** zone property */
	private String zone;

	/** clothing property */
	private String clothing;

	/** climate property */
	private String climate;

	/** languages property */
	private String languages;

	/** best_timevisit property */
	private String best_timevisit;

	/** max_temp property */
	private String max_temp;

	/** avg_rainfall property */
	private String avg_rainfall;

	/** population property */
	private String population;

	/** latitude property */
	private String latitude;

	/** area property */
	private String area;

	/** min_tem property */
	private String min_tem;
	
	private Integer city_id;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the state_id.
	 * @return Integer
	 */
	public Integer getState_id() {
		return state_id;
	}

	/** 
	 * Set the state_id.
	 * @param state_id The state_id to set
	 */
	public void setState_id(Integer state_id) {
		this.state_id = state_id;
	}

	/** 
	 * Returns the logitude.
	 * @return String
	 */
	public String getLogitude() {
		return logitude;
	}

	/** 
	 * Set the logitude.
	 * @param logitude The logitude to set
	 */
	public void setLogitude(String logitude) {
		this.logitude = logitude;
	}

	/** 
	 * Returns the zone.
	 * @return String
	 */
	public String getZone() {
		return zone;
	}

	/** 
	 * Set the zone.
	 * @param zone The zone to set
	 */
	public void setZone(String zone) {
		this.zone = zone;
	}

	/** 
	 * Returns the clothing.
	 * @return String
	 */
	public String getClothing() {
		return clothing;
	}

	/** 
	 * Set the clothing.
	 * @param clothing The clothing to set
	 */
	public void setClothing(String clothing) {
		this.clothing = clothing;
	}

	/** 
	 * Returns the climate.
	 * @return String
	 */
	public String getClimate() {
		return climate;
	}

	/** 
	 * Set the climate.
	 * @param climate The climate to set
	 */
	public void setClimate(String climate) {
		this.climate = climate;
	}

	/** 
	 * Returns the languages.
	 * @return String
	 */
	public String getLanguages() {
		return languages;
	}

	/** 
	 * Set the languages.
	 * @param languages The languages to set
	 */
	public void setLanguages(String languages) {
		this.languages = languages;
	}

	/** 
	 * Returns the best_timevisit.
	 * @return String
	 */
	public String getBest_timevisit() {
		return best_timevisit;
	}

	/** 
	 * Set the best_timevisit.
	 * @param best_timevisit The best_timevisit to set
	 */
	public void setBest_timevisit(String best_timevisit) {
		this.best_timevisit = best_timevisit;
	}

	/** 
	 * Returns the max_temp.
	 * @return Float
	 */
	public String getMax_temp() {
		return max_temp;
	}

	/** 
	 * Set the max_temp.
	 * @param max_temp The max_temp to set
	 */
	public void setMax_temp(String max_temp) {
		this.max_temp = max_temp;
	}

	/** 
	 * Returns the avg_rainfall.
	 * @return String
	 */
	public String getAvg_rainfall() {
		return avg_rainfall;
	}

	/** 
	 * Set the avg_rainfall.
	 * @param avg_rainfall The avg_rainfall to set
	 */
	public void setAvg_rainfall(String avg_rainfall) {
		this.avg_rainfall = avg_rainfall;
	}

	/** 
	 * Returns the population.
	 * @return Float
	 */
	public String getPopulation() {
		return population;
	}

	/** 
	 * Set the population.
	 * @param population The population to set
	 */
	public void setPopulation(String population) {
		this.population = population;
	}

	/** 
	 * Returns the latitude.
	 * @return String
	 */
	public String getLatitude() {
		return latitude;
	}

	/** 
	 * Set the latitude.
	 * @param latitude The latitude to set
	 */
	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	/** 
	 * Returns the area.
	 * @return String
	 */
	public String getArea() {
		return area;
	}

	/** 
	 * Set the area.
	 * @param area The area to set
	 */
	public void setArea(String area) {
		this.area = area;
	}

	/** 
	 * Returns the min_tem.
	 * @return Float
	 */
	public String getMin_tem() {
		return min_tem;
	}

	/** 
	 * Set the min_tem.
	 * @param min_tem The min_tem to set
	 */
	public void setMin_tem(String min_tem) {
		this.min_tem = min_tem;
	}

	public Integer getCity_id() {
		return city_id;
	}

	public void setCity_id(Integer city_id) {
		this.city_id = city_id;
	}
}