/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 09-12-2011
 * 
 * XDoclet definition:
 * @struts.form name="emergencyInfoForm"
 */
public class EmergencyInfoForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** state_id property */
	private Integer state_id;

	/** bbphone_number property */
	private String bbphone_number;

	/** hphone_number property */
	private String hphone_number;

	/** bbaddress property */
	private String bbaddress;

	/** city_id property */
	private Integer city_id;

	/** fire_number property */
	private String fire_number;

	/** hospital_name property */
	private String hospital_name;

	/** haddress property */
	private String haddress;

	/** distcollec_number property */
	private String distcollec_number;

	/** enq_number property */
	private String enq_number;

	/** police_number property */
	private String police_number;

	/** bbank_name property */
	private String bbank_name;

	/** aput_number property */
	private String aput_number;

	/** enq_name property */
	private String enq_name;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the state_id.
	 * @return Integer
	 */
	public Integer getState_id() {
		return state_id;
	}

	/** 
	 * Set the state_id.
	 * @param state_id The state_id to set
	 */
	public void setState_id(Integer state_id) {
		this.state_id = state_id;
	}

	/** 
	 * Returns the bbphone_number.
	 * @return String
	 */
	public String getBbphone_number() {
		return bbphone_number;
	}

	/** 
	 * Set the bbphone_number.
	 * @param bbphone_number The bbphone_number to set
	 */
	public void setBbphone_number(String bbphone_number) {
		this.bbphone_number = bbphone_number;
	}

	/** 
	 * Returns the hphone_number.
	 * @return String
	 */
	public String getHphone_number() {
		return hphone_number;
	}

	/** 
	 * Set the hphone_number.
	 * @param hphone_number The hphone_number to set
	 */
	public void setHphone_number(String hphone_number) {
		this.hphone_number = hphone_number;
	}

	/** 
	 * Returns the bbaddress.
	 * @return String
	 */
	public String getBbaddress() {
		return bbaddress;
	}

	/** 
	 * Set the bbaddress.
	 * @param bbaddress The bbaddress to set
	 */
	public void setBbaddress(String bbaddress) {
		this.bbaddress = bbaddress;
	}

	/** 
	 * Returns the city_id.
	 * @return Integer
	 */
	public Integer getCity_id() {
		return city_id;
	}

	/** 
	 * Set the city_id.
	 * @param city_id The city_id to set
	 */
	public void setCity_id(Integer city_id) {
		this.city_id = city_id;
	}

	/** 
	 * Returns the fire_number.
	 * @return String
	 */
	public String getFire_number() {
		return fire_number;
	}

	/** 
	 * Set the fire_number.
	 * @param fire_number The fire_number to set
	 */
	public void setFire_number(String fire_number) {
		this.fire_number = fire_number;
	}

	/** 
	 * Returns the hospital_name.
	 * @return String
	 */
	public String getHospital_name() {
		return hospital_name;
	}

	/** 
	 * Set the hospital_name.
	 * @param hospital_name The hospital_name to set
	 */
	public void setHospital_name(String hospital_name) {
		this.hospital_name = hospital_name;
	}

	/** 
	 * Returns the haddress.
	 * @return String
	 */
	public String getHaddress() {
		return haddress;
	}

	/** 
	 * Set the haddress.
	 * @param haddress The haddress to set
	 */
	public void setHaddress(String haddress) {
		this.haddress = haddress;
	}

	/** 
	 * Returns the distcollec_number.
	 * @return String
	 */
	public String getDistcollec_number() {
		return distcollec_number;
	}

	/** 
	 * Set the distcollec_number.
	 * @param distcollec_number The distcollec_number to set
	 */
	public void setDistcollec_number(String distcollec_number) {
		this.distcollec_number = distcollec_number;
	}

	/** 
	 * Returns the enq_number.
	 * @return String
	 */
	public String getEnq_number() {
		return enq_number;
	}

	/** 
	 * Set the enq_number.
	 * @param enq_number The enq_number to set
	 */
	public void setEnq_number(String enq_number) {
		this.enq_number = enq_number;
	}

	/** 
	 * Returns the police_number.
	 * @return String
	 */
	public String getPolice_number() {
		return police_number;
	}

	/** 
	 * Set the police_number.
	 * @param police_number The police_number to set
	 */
	public void setPolice_number(String police_number) {
		this.police_number = police_number;
	}

	/** 
	 * Returns the bbank_name.
	 * @return String
	 */
	public String getBbank_name() {
		return bbank_name;
	}

	/** 
	 * Set the bbank_name.
	 * @param bbank_name The bbank_name to set
	 */
	public void setBbank_name(String bbank_name) {
		this.bbank_name = bbank_name;
	}

	/** 
	 * Returns the aput_number.
	 * @return String
	 */
	public String getAput_number() {
		return aput_number;
	}

	/** 
	 * Set the aput_number.
	 * @param aput_number The aput_number to set
	 */
	public void setAput_number(String aput_number) {
		this.aput_number = aput_number;
	}

	/** 
	 * Returns the enq_name.
	 * @return String
	 */
	public String getEnq_name() {
		return enq_name;
	}

	/** 
	 * Set the enq_name.
	 * @param enq_name The enq_name to set
	 */
	public void setEnq_name(String enq_name) {
		this.enq_name = enq_name;
	}
}