/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-01-2011
 * 
 * XDoclet definition:
 * @struts.form name="jobsInfosForm"
 */
public class JobsInfosForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** state_id property */
	private Integer state_id;

	/** comp_name property */
	private String comp_name;

	/** job_name property */
	private String job_name;

	/** city_id property */
	private Integer city_id;

	/** comp_address property */
	private String comp_address;

	/** comp_phno property */
	private String comp_phno;

	/** qualification property */
	private String qualification;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the state_id.
	 * @return Integer
	 */
	public Integer getState_id() {
		return state_id;
	}

	/** 
	 * Set the state_id.
	 * @param state_id The state_id to set
	 */
	public void setState_id(Integer state_id) {
		this.state_id = state_id;
	}

	/** 
	 * Returns the comp_name.
	 * @return String
	 */
	public String getComp_name() {
		return comp_name;
	}

	/** 
	 * Set the comp_name.
	 * @param comp_name The comp_name to set
	 */
	public void setComp_name(String comp_name) {
		this.comp_name = comp_name;
	}

	/** 
	 * Returns the job_name.
	 * @return String
	 */
	public String getJob_name() {
		return job_name;
	}

	/** 
	 * Set the job_name.
	 * @param job_name The job_name to set
	 */
	public void setJob_name(String job_name) {
		this.job_name = job_name;
	}

	/** 
	 * Returns the city_id.
	 * @return Integer
	 */
	public Integer getCity_id() {
		return city_id;
	}

	/** 
	 * Set the city_id.
	 * @param city_id The city_id to set
	 */
	public void setCity_id(Integer city_id) {
		this.city_id = city_id;
	}

	/** 
	 * Returns the comp_address.
	 * @return String
	 */
	public String getComp_address() {
		return comp_address;
	}

	/** 
	 * Set the comp_address.
	 * @param comp_address The comp_address to set
	 */
	public void setComp_address(String comp_address) {
		this.comp_address = comp_address;
	}

	/** 
	 * Returns the comp_phno.
	 * @return String
	 */
	public String getComp_phno() {
		return comp_phno;
	}

	/** 
	 * Set the comp_phno.
	 * @param comp_phno The comp_phno to set
	 */
	public void setComp_phno(String comp_phno) {
		this.comp_phno = comp_phno;
	}

	/** 
	 * Returns the qualification.
	 * @return String
	 */
	public String getQualification() {
		return qualification;
	}

	/** 
	 * Set the qualification.
	 * @param qualification The qualification to set
	 */
	public void setQualification(String qualification) {
		this.qualification = qualification;
	}
}