/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-14-2011
 * 
 * XDoclet definition:
 * @struts.form name="MessageForm"
 */
public class MessageForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** senddate property */
	private String senddate;

	/** to property */
	private String to;

	/** senddate1 property */
	private String senddate1;

	/** messageid property */
	private int messageid;

	/** message property */
	private String message;

	/** from property */
	private String from;

	/** subject property */
	private String subject;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the senddate.
	 * @return String
	 */
	public String getSenddate() {
		return senddate;
	}

	/** 
	 * Set the senddate.
	 * @param senddate The senddate to set
	 */
	public void setSenddate(String senddate) {
		this.senddate = senddate;
	}

	/** 
	 * Returns the to.
	 * @return String
	 */
	public String getTo() {
		return to;
	}

	/** 
	 * Set the to.
	 * @param to The to to set
	 */
	public void setTo(String to) {
		this.to = to;
	}

	/** 
	 * Returns the senddate1.
	 * @return String
	 */
	public String getSenddate1() {
		return senddate1;
	}

	/** 
	 * Set the senddate1.
	 * @param senddate1 The senddate1 to set
	 */
	public void setSenddate1(String senddate1) {
		this.senddate1 = senddate1;
	}

	/** 
	 * Returns the messageid.
	 * @return int
	 */
	public int getMessageid() {
		return messageid;
	}

	/** 
	 * Set the messageid.
	 * @param messageid The messageid to set
	 */
	public void setMessageid(int messageid) {
		this.messageid = messageid;
	}

	/** 
	 * Returns the message.
	 * @return String
	 */
	public String getMessage() {
		return message;
	}

	/** 
	 * Set the message.
	 * @param message The message to set
	 */
	public void setMessage(String message) {
		this.message = message;
	}

	/** 
	 * Returns the from.
	 * @return String
	 */
	public String getFrom() {
		return from;
	}

	/** 
	 * Set the from.
	 * @param from The from to set
	 */
	public void setFrom(String from) {
		this.from = from;
	}

	/** 
	 * Returns the subject.
	 * @return String
	 */
	public String getSubject() {
		return subject;
	}

	/** 
	 * Set the subject.
	 * @param subject The subject to set
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}
}