/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 09-09-2011
 * 
 * XDoclet definition:
 * @struts.form name="placesForm"
 */
public class PlacesForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** phone property */
	private String phone;

	/** img property */
	private String img;

	/** place property */
	private String place;

	/** placeid property */
	private int placeid;

	/** history property */
	private String history;

	/** cityid property */
	private int cityid;

	/** location property */
	private String location;

	/** cityname property */
	private String cityname;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the phone.
	 * @return String
	 */
	public String getPhone() {
		return phone;
	}

	/** 
	 * Set the phone.
	 * @param phone The phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/** 
	 * Returns the img.
	 * @return String
	 */
	public String getImg() {
		return img;
	}

	/** 
	 * Set the img.
	 * @param img The img to set
	 */
	public void setImg(String img) {
		this.img = img;
	}

	/** 
	 * Returns the place.
	 * @return String
	 */
	public String getPlace() {
		return place;
	}

	/** 
	 * Set the place.
	 * @param place The place to set
	 */
	public void setPlace(String place) {
		this.place = place;
	}

	/** 
	 * Returns the placeid.
	 * @return int
	 */
	public int getPlaceid() {
		return placeid;
	}

	/** 
	 * Set the placeid.
	 * @param placeid The placeid to set
	 */
	public void setPlaceid(int placeid) {
		this.placeid = placeid;
	}

	/** 
	 * Returns the history.
	 * @return String
	 */
	public String getHistory() {
		return history;
	}

	/** 
	 * Set the history.
	 * @param history The history to set
	 */
	public void setHistory(String history) {
		this.history = history;
	}

	/** 
	 * Returns the cityid.
	 * @return int
	 */
	public int getCityid() {
		return cityid;
	}

	/** 
	 * Set the cityid.
	 * @param cityid The cityid to set
	 */
	public void setCityid(int cityid) {
		this.cityid = cityid;
	}

	/** 
	 * Returns the location.
	 * @return String
	 */
	public String getLocation() {
		return location;
	}

	/** 
	 * Set the location.
	 * @param location The location to set
	 */
	public void setLocation(String location) {
		this.location = location;
	}

	/** 
	 * Returns the cityname.
	 * @return String
	 */
	public String getCityname() {
		return cityname;
	}

	/** 
	 * Set the cityname.
	 * @param cityname The cityname to set
	 */
	public void setCityname(String cityname) {
		this.cityname = cityname;
	}
}