/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smart.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 09-10-2011
 * 
 * XDoclet definition:
 * @struts.form name="shopsForm"
 */
public class ShopsForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** phone property */
	private String phone;

	/** shopid property */
	private int shopid;

	/** famousfor property */
	private String famousfor;

	/** shopname property */
	private String shopname;

	/** address property */
	private String address;

	/** cityid property */
	private int cityid;

	/** cityname property */
	private String cityname;

	/** offers property */
	private String offers;
	
	private Integer state_id;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the phone.
	 * @return String
	 */
	public String getPhone() {
		return phone;
	}

	/** 
	 * Set the phone.
	 * @param phone The phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/** 
	 * Returns the shopid.
	 * @return int
	 */
	public int getShopid() {
		return shopid;
	}

	/** 
	 * Set the shopid.
	 * @param shopid The shopid to set
	 */
	public void setShopid(int shopid) {
		this.shopid = shopid;
	}

	/** 
	 * Returns the famousfor.
	 * @return String
	 */
	public String getFamousfor() {
		return famousfor;
	}

	/** 
	 * Set the famousfor.
	 * @param famousfor The famousfor to set
	 */
	public void setFamousfor(String famousfor) {
		this.famousfor = famousfor;
	}

	/** 
	 * Returns the shopname.
	 * @return String
	 */
	public String getShopname() {
		return shopname;
	}

	/** 
	 * Set the shopname.
	 * @param shopname The shopname to set
	 */
	public void setShopname(String shopname) {
		this.shopname = shopname;
	}

	/** 
	 * Returns the address.
	 * @return String
	 */
	public String getAddress() {
		return address;
	}

	/** 
	 * Set the address.
	 * @param address The address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/** 
	 * Returns the cityid.
	 * @return int
	 */
	public int getCityid() {
		return cityid;
	}

	/** 
	 * Set the cityid.
	 * @param cityid The cityid to set
	 */
	public void setCityid(int cityid) {
		this.cityid = cityid;
	}

	/** 
	 * Returns the cityname.
	 * @return String
	 */
	public String getCityname() {
		return cityname;
	}

	/** 
	 * Set the cityname.
	 * @param cityname The cityname to set
	 */
	public void setCityname(String cityname) {
		this.cityname = cityname;
	}

	/** 
	 * Returns the offers.
	 * @return String
	 */
	public String getOffers() {
		return offers;
	}

	/** 
	 * Set the offers.
	 * @param offers The offers to set
	 */
	public void setOffers(String offers) {
		this.offers = offers;
	}

	public Integer getState_id() {
		return state_id;
	}

	public void setState_id(Integer state_id) {
		this.state_id = state_id;
	}

	
}